image:
  registry: docker.io
  repository: kilo1089/database-service
  tag: latest

tomcatAllowRemoteManagement: 1

persistence:
  enabled: false

service:
  type: NodePort
  nodePort: "31181"  # dev(31181), qa(31182), prod(31183)

extraEnvVars:
  - name: JAVA_OPTS
    value: '-Dspring.profiles.active=dev'